name: Build Release

on:
  release:
    branches:
      - main
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_EVENT: ${{ github.event_name }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: current
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build and Test
        run: chmod +x gradlew && ./gradlew clean test
      - name: Verify Javadoc
        run: ./gradlew javadoc
      - name: Verify, Sign and Publish Release
        run: ./gradlew -i publishToSonatype closeAndReleaseSonatypeStagingRepository
